[project]
name = "fastapi-web-reader"
version = "0.1.0"
description = "A simple API to read books and your own library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff]
line-length = 79
select = ["ALL"]
ignore = ["D100", "D101", "D103"]
