"""unique ch num

Revision ID: 4e82d7bcdade
Revises: 
Create Date: 2025-06-24 15:02:00.459481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e82d7bcdade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_chapter_number_key'), 'chapters', type_='unique')
    op.create_unique_constraint('uq_chapter_number_volume_id', 'chapters', ['chapter_number', 'volume_id'])
    op.drop_constraint(op.f('volumes_volume_number_key'), 'volumes', type_='unique')
    op.create_unique_constraint('uq_volume_number_book_id', 'volumes', ['volume_number', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_volume_number_book_id', 'volumes', type_='unique')
    op.create_unique_constraint(op.f('volumes_volume_number_key'), 'volumes', ['volume_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_chapter_number_volume_id', 'chapters', type_='unique')
    op.create_unique_constraint(op.f('chapters_chapter_number_key'), 'chapters', ['chapter_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
