"""enum naming.

Revision ID: 62caa81583ec
Revises: cdd7eb92d35e
Create Date: 2025-06-19 23:54:28.347772

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "62caa81583ec"
down_revision: str | None = "cdd7eb92d35e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="book_shelf_enum",
        new_values=["Reading", "Have read", "To read", "Favorites"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users_books",
                column_name="book_shelf",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="book_shelf_enum",
        new_values=["Reading", "Have read", "TO read", "Favorites"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="users_books",
                column_name="book_shelf",
            ),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
