"""TranslationStatusEnum removed from db

Revision ID: a8c88279f7aa
Revises: b6993e7b4940
Create Date: 2025-07-19 15:26:31.381500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8c88279f7aa"
down_revision: str | None = "b6993e7b4940"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "book_translation_status",
        existing_type=postgresql.ENUM(
            "Translated",
            "In progress",
            "Abandoned",
            "Absent",
            name="translation_status_enum",
        ),
        type_=sa.String(length=50),
        nullable=False,
    )
    sa.Enum(
        "Translated",
        "In progress",
        "Abandoned",
        "Absent",
        name="translation_status_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "Translated",
        "In progress",
        "Abandoned",
        "Absent",
        name="translation_status_enum",
    ).create(op.get_bind())
    op.alter_column(
        "books",
        "book_translation_status",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "Translated",
            "In progress",
            "Abandoned",
            "Absent",
            name="translation_status_enum",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
