"""users_books rels

Revision ID: bc80799c494c
Revises:
Create Date: 2025-06-26 20:20:04.770048

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bc80799c494c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
